test:
  adapter: postgresql
  encoding: unicode
  database: trivia_gpt_test
  pool: 10
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || ''%>
  host: localhost
  port: 5432

development:
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= ENV['POSTGRES_HOST'] || '' %>
  database: trivia_gpt_development
  adapter: postgresql
  encoding: unicode
  pool: 50
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: <%= "#{ENV['DATABASE_NAME']}-staging" || '' %>
  pool: <%= ENV['DB_POOL'].to_i rescue 50 %>
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= ENV['POSTGRES_HOST'] || '' %>
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: <%= "#{ENV['DATABASE_NAME']}-production" || '' %>
  pool: <%= ENV['DB_POOL'].to_i rescue 50 %>
  username: <%= ENV['POSTGRES_USER'] || '' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  host: <%= ENV['POSTGRES_HOST'] || '' %>
  port: 5432
